trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2  
  displayName: Scaling $(AppServicePlan) to $(SKU)
  inputs:
    azureSubscription: $(AzureSubscription)
    scriptType: 'pscore'
    scriptLocation: 'scriptPath'
    arguments: '$(AppServicePlan) $(ResourceGroup) $(SKU)'
    scriptPath: './src/app-service-plan/Scale-AppServicePlan.ps1'
